name: Registrar plantilla de tarea
run-name: "Anotación de la plantilla '${{ github.event.client_payload.repository.name }}'"

on:
  repository_dispatch:
    types: 
      - template-repo-created

jobs:
  registrar-repositorio:
    uses: ./.github/workflows/repo-register.yaml
    with:
      event: ${{ toJSON(github.event) }}
      regfile: plantillas.json
      branch: plantillas
      debug: false
    secrets:
      ORGANIZATION_ACCESS_TOKEN: ${{ secrets.ORGANIZATION_ACCESS_TOKEN }}
    permissions:
      contents: write
